### ISSUE TITLE
Support native json spinner field

### ISSUE THREAD

**Issue by WinnyTroy** [OpenSRP/xlson#20]
The spinner field is XLSForm's select multiple type.

survey sheet

type | name | label
-- | -- | --
select multiple moods | user_spinner | What is the mood?

choices sheet

list name | name | label | instance::openmrs_entity_id
-- | -- | -- | --
moods | happy | Happy | 1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
moods | sad | Sad | 1713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
moods | somber | Somber | 2113AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

```JSON
{
      "name": "user_spinner",
      "label": "What is the mood?",
      "type": "select all that apply",
      "children": [
        {
          "name": "happy",
          "label": "Happy",
          "instance": {
            "openmrs_entity_id": "1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        },
        {
          "name": "sad",
          "label": "Sad",
          "instance": {
            "openmrs_entity_id": "1713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        },
        {
          "name": "somber",
          "label": "Somber",
          "instance": {
            "openmrs_entity_id": "2113AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        }
      ]
    }
```

The resulting native form JSON is:

```JSON
{
  "key": "user_spinner",
  "openmrs_entity_parent": "",
  "openmrs_entity": "",
  "openmrs_entity_id": "",
  "type": "spinner",
  "hint": "What is the mood?",
  "values": [
    "Happy",
    "Sad",
    "Somber"
  ],
  "keys": [
    "happy",
    "sad",
    "somber"
  ],
  "openmrs_choice_ids": {
    "happy": "1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "sad": "1713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "somber": "2113AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  }
}
```

**Comment by allan-on** [comment]
The Spinner field is XLSForm's select *one* type

> The previous Spinner implementation was refactored to a Checkbox support implementation since it was a select multiple implementation. This is described in  https://github.com/OpenSRP/xlson/issues/41 & code changed in this PR https://github.com/OpenSRP/xlson/pull/43
