### ISSUE TITLE
Support gps field

### ISSUE THREAD

**Issue by ukanga** [OpenSRP/xlson#5]
type               | name         | label                        |
------------------|---------------|--------------------------|
 begin group  | step1         | Patient Information  |
 gps                | user_gps   | Capture GPS location |
 end group     |                   |                                |

XLSForm JSON field:
```JSON
{
        "name": "user_gps",
        "label": "Capture GPS location",
        "type": "geopoint"
}
```

The native form JSON format as:

```JSON
{
  "key": "user_gps",
  "openmrs_entity_parent": "",
  "openmrs_entity": "",
  "openmrs_entity_id": "",
  "openmrs_data_type": "text",
  "type": "gps"
}
```

**Comment by ukanga** [comment]
@dubdabasoduba Which native form field does the label go to or does the GPS field not have a label field?

**Comment by dubdabasoduba** [comment]
We use the label widget.  Its defined here https://github.com/OpenSRP/opensrp-client-native-form/blob/master/sample/src/main/assets/json.form/basic_form.json starting line `316-325`

**Comment by ukanga** [comment]
@dubdabasoduba does that mean we should then add two fields when we add a GPS field? Where the label appears immediately after the GPS field?


```JSON
{
  "key": "user_gps",
  "openmrs_entity_parent": "",
  "openmrs_entity": "",
  "openmrs_entity_id": "",
  "openmrs_data_type": "text",
  "type": "gps"
},
{
    "key": "user_gps_label",
    "type": "label",
    "text": "Capture GPS location"
}
```

**Comment by dubdabasoduba** [comment]
@WinnyTroy @ukanga  yes we need two but it mostly depends on the data dictionary. If the data dictionary says we have a label we shall have 2 if it doesn't we only have the gps widget.
